# Generated by Django 4.2.1 on 2023-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_encuestas', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
