# Generated by Django 4.2.1 on 2023-05-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_encuestas', '0003_alter_user_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
