# Generated by Django 4.2.1 on 2023-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_encuestas', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='delete_at',
            field=models.DateTimeField(null=None),
        ),
        migrations.AlterField(
            model_name='domain',
            name='delete_at',
            field=models.DateTimeField(null=None),
        ),
    ]
