# Generated by Django 4.2.1 on 2023-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_encuestas', '0005_alter_company_delete_at_alter_domain_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
    ]
