# Generated by Django 4.2.1 on 2023-05-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_encuestas', '0006_alter_company_delete_at_alter_domain_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
